import Head from 'next/head'
import styled from 'styled-components';
import React, { FunctionComponent } from 'react'
import Invoices from '@/components/invoices';
import Toolbar from '@/components/toolbar';
import ListHeader from '@/components/list-header'

const Wrapper = styled.div`
  padding: 72px 0;
  max-width: 730px;
  margin: 0 auto;
`

const Home: FunctionComponent = () => {
  return (
    <div>
      <Head>
        <title>Invoice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Toolbar />
        <Wrapper>
          <ListHeader />
          <Invoices />
        </Wrapper>
      </main>
    </div>
  )
}

export default Home
